version: '3.8'
 
services:
 
  web:
   container_name: core_game
   build: .
   restart: always
   env_file: ./Game2048/.env
   volumes:
     - .:/Game2048
     - static_volume:/Game2048/static
 
   ports:
     - 80:8000
 
 
 
volumes:
  static_volume:
